[package]
name = "rust_fswatch"
version = "0.1.0"
authors = ["Ryota Nishi <nishi@swlab.cs.okayama-u.ac.jp>"]
edition = "2018"
links = "fsw"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
libc = "0.2"